#!/bin/bash
#
# repo-config

# Autor: Charlie Martínez ®
# Licencia GPLv3

# Activa o desactiva los repositorios non-free y contrib
# de Debian Buster  

clear

opc=$(zenity --width=640 --height=480 --title=Quirinux --entry --text="
  		ACTIVAR O DESACTIVAR FLATPAK

	Activa o desactiva el soporte para instalar programas almacenados
	como repositorios portables tipo Flatpak. Este programa también 
	sirve para agregarlos o quitarlos al catálogo del Centro de 
	Software de Mint LMDE4.

	ADVERTENCIA: Si tiene programas Flatpak instalados y desactiva
	esta opción, esos programas también se desinstalarán. 
		
		1) Activar Flatpak
		2) Desactivar Flatpak
		0) Salir
"
)
case $opc in
"1") 
(

echo "# Activando soporte para Flatpak..."; sleep 1s

sudo apt-get update -y
sudo apt-get install flatpak -y
sudo apt-get install -f -y
sudo apt-get autoremove --purge -y
sudo apt-get reinstall mintinstall -y
sudo rm /usr/share/applications/mintinstall.desktop
sudo cp /opt/mintinstall/applications/* /usr/share/applications/
sudo cp /opt/mintinstall/icons/* /usr/share/icons/

)|

zenity --progress --pulsate --auto-close
title="Quirinux"
percentage=0

;;

"2")

echo "# Desactivando soporte para Flatpak..."; sleep 1s

sudo apt-get update -y
sudo apt-get remove --purge flatpak -y
sudo apt-get install -f -y
sudo apt-get autoremove --purge -y

;;


"0")

	exit 0
;; 
esac 